target-version = "py312"
line-length = 120

exclude = [
    ".venv",
    "__pycache__",
    "migrations",
    "build",
    "dist",
    "alembic",
    "docker"
]

fix = true
unsafe-fixes = false

[format]
quote-style = "single"
indent-style = "space"


[lint]
extend-select = [
    "UP", "D", "E", "PL", "I", "N", "ASYNC", "FAST",
    "ANN", "TCH"
]


[lint.flake8-annotations]
suppress-none-returning = false
suppress-dummy-args = true
allow-star-arg-any = false
mypy-init-return = true


[lint.pydocstyle]
convention = "google"


[lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "double"
docstring-quotes = "double"
