"""init

Revision ID: b68f6f733f5e
Revises: 
Create Date: 2025-10-07 12:14:32.760610

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'b68f6f733f5e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
